### ISSUE TITLE
Allow SOPS to take a pathlib.Path object as first parameter

### ISSUE THREAD

**Issue by voidus** [nikaro/sopsy#67]
I think using `Path`s over strings for file paths is generally good practice. This isn't hugely important since it's always possible to do `Sops(str(my_path))` but it would still be nice.

Thanks for creating this btw!

**Comment by nikaro** [comment]
Hello, thanks for opening the issue. Did you had any error passing a `Path()` to `Sops()`? It should already work 🤔 

Only your type checker may not be happy, https://github.com/nikaro/sopsy/pull/68 should fix this. Let me know if this would be sufficient to you.

**Comment by voidus** [comment]
Yes exactly. My understanding is that most code that optimistically handles paths "just works" with `Path`s, but with type checkers being integrated in a lot of CI pipelines, #68 looks great :)
