### ISSUE TITLE
More permissive license without copyleft

### ISSUE THREAD

**Issue by pavelzw** [nikaro/sopsy#78]
Hi @nikaro,

I would like to use this project in a context where I am not able to license the work in GPL.
Would it be possible to distribute this project with a License that is not as restrictive as GPL-3.0, for example `LGPL-3.0-or-later` (see [Wikipedia](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License#Differences_from_the_GPL))?

Otherwise i would need to call the sops binary myself in my work instead of using sopsy.

If you don't want to change your license, feel free to close this issue, no hard feelings :)

**Comment by nikaro** [comment]
Hello @pavelzw, i don't mind :-) I will change for MIT.

**Comment by pavelzw** [comment]
Thanks @nikaro!

it looks like the pypi release didn't go through though: https://github.com/nikaro/sopsy/actions/runs/11895478062/job/33145233862

**Comment by nikaro** [comment]
This is good now! 🙏
